# Generated by Django 3.2 on 2022-03-10 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('email', models.EmailField(max_length=35, verbose_name='邮箱')),
                ('ge_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 10, 2, 45, 47, 900766, tzinfo=utc), verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
    ]
