# Generated by Django 3.2 on 2022-03-29 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='ge_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='生成时间'),
        ),
    ]
