# Generated by Django 3.2 on 2022-05-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
